jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-latest'
  timeoutInMinutes: 60

  strategy:
    matrix:
      Python36:
        CONDA_PY: '3.6'
        CONDA_NPY: '1.11'
      Python37:
        CONDA_PY: '3.7'
        CONDA_NPY: '1.17'
    maxParallel: 10
  
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: sudo install -d -m 0777 /usr/envs
    displayName: Fix conda permissions

  - bash: |
      conda config --set always_yes yes --set changeps1 no
      conda config --add channels conda-forge
      conda create -n test-environment python=3.7 --file requirements.txt
      source activate test-environment
    displayName: Create new conda environment

  - bash: |
      source activate test-environment
      pip install -e .
    displayName: Installing analysis
    
  - bash: |
      source activate test-environment
      python -m pytest -v
    displayName: Running tests